fix FTBS on name clash between linux/input.h and xf86str.h
Since we don't need those, it's best to just #undef them, after
including xf86str.h.

> In file included from /usr/include/xorg/os.h:53:
> /usr/include/string.h:149:10: note: previous declaration of 'timingsafe_memcmp' with type 'int(const void *, const void *, size_t)' {aka 'int(const void *, const void *, long unsigned int)'}
>   149 | int      timingsafe_memcmp(const void *, const void *, size_t);
>       |          ^~~~~~~~~~~~~~~~~
> In file included from ../../../src/spiceqxl_uinput.c:12:
> /usr/include/xorg/xf86str.h:263:5: error: expected identifier before numeric constant
>   263 |     BUS_PCI,
>       |     ^~~~~~~

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>